sources:
  - name: Movies
    handler:
      neo4j:
        database: movies
        password: movies
        url: bolt+s://demo.neo4jlabs.com:7687
        username: movies

documents:
  - ./src/graphql/**/*.*.graphql

serve:
  playground: false
