name: 'Setup the environment'
description: 'Install Node, PNPM, project dependencies and get NX SHAs'
inputs:
  ignore-cypress-cache:
    description: Skip the restore of global Cypress cache (if cache is found)
    required: false
    default: 'false'
  node-version:
    description: The node version to use.
    required: false
    default: 'config'

runs:
  using: 'composite'
  steps:
    - name: Setup Volta
      if: inputs.node-version == 'config'
      uses: volta-cli/action@76620aa011ba56028bb0bae35caa5f9b6118c8c7 # tag=v1.7.0

    - name: Setup Volta
      if: inputs.node-version != 'config'
      uses: volta-cli/action@76620aa011ba56028bb0bae35caa5f9b6118c8c7 # tag=v1.7.0
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cypress Cache
      uses: actions/cache@0865c47f36e68161719c5b124609996bb5c40129 # tag=v3
      id: cypress-cache
      if: inputs.ignore-cypress-cache != 'true'
      with:
        path: |
          ~/.cache/Cypress
        key: ${{ runner.os }}-${{ inputs.node-version }}-cypress-dep-cache-v1-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.node-version }}-cypress-dep-cache-v1-

    - name: PNPM Repo Cache
      uses: actions/cache@0865c47f36e68161719c5b124609996bb5c40129 # tag=v3
      id: pnpm-repo-cache
      with:
        path: |
          **/node_modules
          !**/node_modules/.cache/nx
        key: ${{ runner.os }}-${{ inputs.node-version }}-pnpm-dep-cache-v1-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.node-version }}-pnpm-dep-cache-v1-

    - uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Get pnpm cache directory path
      id: pnpm-cache-dir-path
      if: steps.pnpm-repo-cache.outputs.cache-hit != 'true'
      shell: bash
      run: echo "::set-output name=dir::$(pnpm store path)"

    - name: PNPM Store Cache
      uses: actions/cache@0865c47f36e68161719c5b124609996bb5c40129 # tag=v3
      id: pnpm-global-cache
      if: steps.pnpm-repo-cache.outputs.cache-hit != 'true'
      with:
        path: |
          ${{ steps.pnpm-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-${{ inputs.node-version }}-pnpm-global-cache-v1-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.node-version }}-pnpm-global-cache-v1-

    - name: Install Node Dependencies
      if: steps.pnpm-repo-cache.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Nx Shas
      uses: nrwl/nx-set-shas@a80e36fdf700047d299324529b0f0eadc1a38cb2 # tag=v2.2.2
