name: 'Setup the environment'
description: 'Install Node, PNPM, project dependencies and get NX SHAs'
runs:
  using: 'composite'
  steps:
    - name: Check out repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      with:
        fetch-depth: 0

    - name: Setup Volta
      uses: volta-cli/action@76620aa011ba56028bb0bae35caa5f9b6118c8c7 # tag=v1.7.0

    - uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Get pnpm cache directory path
      id: pnpm-cache-dir-path
      shell: bash
      run: echo "::set-output name=dir::$(pnpm store path)"

    - name: Cypress Cache
      uses: actions/cache@c3f1317a9e7b1ef106c153ac8c0f00fed3ddbc0d # tag=v3
      id: cypress-cache
      with:
        path: |
          ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-dep-cache-v1-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-cypress-dep-cache-v1-

    - name: PNPM Cache
      uses: actions/cache@c3f1317a9e7b1ef106c153ac8c0f00fed3ddbc0d # tag=v3
      id: pnpm-cache
      with:
        path: |
          **/node_modules
          ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          !**/node_modules/.cache/nx
        key: ${{ runner.os }}-pnpm-dep-cache-v4-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-dep-cache-v4-

    - name: Install Node Dependencies
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Nx Shas
      uses: nrwl/nx-set-shas@a80e36fdf700047d299324529b0f0eadc1a38cb2 # tag=v2.2.2
