name: 'Code Analysis - ESLint'

on:
  workflow_call:
    secrets:
      NX_CLOUD_ACCESS_TOKEN:
        description: 'The NX Cloud API token'
        required: true

concurrency:
  group: code-analysis--eslint-${{ github.workflow }}-${{ github.ref }}

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        project:
          - example-api-gateway-openapi-javascript-wiki
          - example-api-gateway-openapi-javascript-wiki-e2e
          - example-sdk-graphql-star-wars-api
          - example-sdk-json-schema-fake-api
          - example-sdk-mysql-rfam
          - example-sdk-neo4j-movies
          - example-sdk-nextjs
          - example-sdk-nextjs-e2e
          - example-sdk-odata-trippin
          - example-sdk-openapi-javascript-wiki
          - example-sdk-openapi-stackexchange
          - example-sdk-soap-country-info
          - nx-mesh
    steps:
      - name: Check out repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
        with:
          fetch-depth: 0

      - name: Setup Job
        uses: ./.github/actions/setup-job
        with:
          node_version: lts

      - name: Lint ${{ matrix.project }}
        continue-on-error: true
        run: |
          pnpm nx run ${{ matrix.project }}:lint \
            --format @microsoft/eslint-formatter-sarif \
            --output-file ${{ matrix.project }}-eslint-results.sarif

      - name: Upload ${{ matrix.project }} lint results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: reports/libs/nx-mesh/lint.sarif
          wait-for-processing: true
