name: 'Deploy to Vercel'

on:
  workflow_call:
    inputs:
      name:
        description: App Name
        type: string
        required: true
      environment:
        description: >
          GitHub deployment environment
        type: string
        required: true
      production:
        description: Deploy production?
        type: boolean
        required: false
        default: false
    secrets:
      VERCEL_ORG_ID:
        description: 'The Vercel ORG ID'
        required: true
      VERCEL_PROJECT_ID:
        description: 'The Vercel Project Id'
        required: true
      VERCEL_TOKEN:
        description: 'The Vercel API token'
        required: true

concurrency:
  group: deploy-vercel--${{ github.workflow }}-${{ github.ref }}--${{ inputs.name }}--${{ inputs.production }}--${{ inputs.environment }}

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy ${{ inputs.name }} to Vercel (Production = ${{ inputs.production }})
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }} (${{ steps.deploy-env.outputs.name }})
      url: ${{ steps.vercel.outputs.PREVIEW_URL }}
    steps:
      - name: Check out repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
        with:
          fetch-depth: 0

      - name: Deploy env
        id: deploy-env
        shell: bash
        run: |
          name=Preview

          if [ ${{ inputs.production }} = true ]; then
            name=Production
          fi

          echo The env is $name
          echo ::set-output name=name::$name

      - name: Deploy to Vercel
        id: vercel
        uses: BetaHuhn/deploy-to-vercel-action@8aec30fa2a289649346e38660b9eb1f011bb4a65 # v1
        with:
          GITHUB_DEPLOYMENT_ENV: ${{ inputs.environment }} (${{ steps.deploy-env.outputs.name }})
          GITHUB_DEPLOYMENT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_LABELS: vercel
          PRODUCTION: ${{ inputs.production }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
