name: 'Lint'

on:
  workflow_call:
    inputs:
      affected:
        description: >
          Run for affected projects.
        required: false
        default: true
        type: boolean
      node_version:
        description: >
          Optionally define the version of Node to install via Volta.

          Pass `config` (default value) to use the Volta config.
        required: false
        default: 'config'
        type: string
      save_cache:
        description: >
          Should the cache be saved upon completion?
        required: false
        default: false
        type: boolean
    secrets:
      NX_CLOUD_ACCESS_TOKEN:
        description: 'The NX Cloud API token'
        required: true

concurrency:
  group: lint--${{ github.workflow }}--${{ github.ref }}

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  lint:
    name: Lint & Prettier
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Job
        uses: ./.github/actions/setup-job
        with:
          node-version: ${{ inputs.node_version }}
          save-cache: '${{ inputs.save_cache }}'

      - name: Workspace Lint
        run: |
          pnpm nx-cloud record -- npx nx workspace-lint

      - name: Format
        run: |
          pnpm nx-cloud record -- npx nx format:check

      - name: Affected Lint
        if: inputs.affected == true
        run: |
          pnpm nx affected \
            --target=lint \
            --parallel=4

      - name: Lint
        if: inputs.affected != true
        run: |
          pnpm nx run-many \
            --target=lint \
            --parallel=4 \
            --all
