name: 'Build & Test'

env:
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_TOKEN }}
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_RUN_GROUP: ${{ github.run_id }}

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      # Enable tmate debugging of manually-triggered workflows
      # if the input option was provided.
      - name: Setup SSH debug session
        uses: mxschmitt/action-tmate@8b4e4ac71822ed7e0ad5fb3d1c33483e9e8fb270 # tag=v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build & Test
        uses: ./.github/actions/build-test
        env:
          NX_CLOUD_AUTH_TOKEN: ${{ env.NX_CLOUD_AUTH_TOKEN }}
          NX_CLOUD_DISTRIBUTED_EXECUTION: ${{ env.NX_CLOUD_DISTRIBUTED_EXECUTION }}
          NX_RUN_GROUP: ${{ env.NX_RUN_GROUP }}

  agents:
    runs-on: ubuntu-latest
    name: Nx Agent
    strategy:
      matrix:
        agent: [1, 2]
    steps:
      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Start Nx Agent ${{ matrix.agent }}
        run: pnpm nx-cloud start-agent
