name: 'Build & Test'

on:
  workflow_call:
    inputs:
      affected:
        description: Only build & test affected apps & libraries.
        type: boolean
        required: false
        default: true
      parallel:
        description: Max number of parallel processes per Nx target
        type: number
        required: false
        default: 3
    outputs:
      affectedApps:
        description: 'The affected apps'
        value: ${{ jobs.build-test.outputs.affectedApps }}
    secrets:
      NX__TRIPPIN__API_KEY:
        description: 'The Trippin API Key'
        required: true
      NX__WEATHERBIT__API_KEY:
        description: 'The Weatherbit API Key'
        required: true
      NX_CLOUD_ACCESS_TOKEN:
        description: 'The NX Cloud API token'
        required: true

concurrency:
  group: build-test-${{ github.workflow }}-${{ github.ref }}

env:
  NX__TRIPPIN__API_KEY: ${{ secrets.NX__TRIPPIN__API_KEY }}
  NX__WEATHERBIT__API_KEY: ${{ secrets.NX__WEATHERBIT__API_KEY }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      affectedAgents: ${{ steps.affectedAgents.agents }}
      hasAgents: ${{ steps.affectedAgents.hasAgents }}
    steps:
      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Affected Agents Matrix
        id: affectedAgents
        uses: ./.github/actions/set-nx-agents-matrix

  nx:
    name: Nx Affected
    runs-on: ubuntu-latest
    needs: [setup]
    timeout-minutes: 10
    strategy:
      matrix:
        command:
          - [Build, 'nx affected --target=build --parallel=3']
          - [
              Lint,
              'nx-cloud record -- npx nx workspace-lint; pnpm nx-cloud record -- npx nx format:check; pnpm nx affected --target=lint --parallel=3',
            ]
          - [
              Test,
              'nx affected --target=test --parallel=3 --ci --code-coverage',
            ]
          - [Validate, 'nx affected --target=validate --parallel=3']
          - [E2E, 'nx affected --target=e2e --parallel=3']
          - [
              'E2E (Start)',
              'nx affected --target=e2e --configuration=start --parallel=3',
            ]
    steps:
      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          ignore-pnpm-global-cache: true
          ignore-cypress-cache: ${{ !startsWith(matrix.command[0], 'E2E') }}

      - name: Affected ${{ matrix.command[0] }}
        shell: bash
        run: |
          pnpm ${{ matrix.command[1] }}
