name: 'Build & Test'

on:
  workflow_call:
    inputs:
      affected:
        description: Only build & test affected apps & libraries.
        type: boolean
        required: false
        default: true
    outputs:
      affected:
        description: 'Affected apps & libraries'
        value: ${{ jobs.setup.outputs.affected }}
      affectedLength:
        description: 'Number of affected apps & libraries'
        value: ${{ jobs.setup.outputs.affectedLength }}
      affectedApps:
        description: 'Affected apps'
        value: ${{ jobs.setup.outputs.affectedApps }}
      affectedAppsLength:
        description: 'Number of affected apps'
        value: ${{ jobs.setup.outputs.affectedAppsLength }}
      affectedLibs:
        description: 'Affected libraries'
        value: ${{ jobs.setup.outputs.affectedLibs }}
      affectedLibsLength:
        description: 'Number of affected libraries'
        value: ${{ jobs.setup.outputs.affectedLibsLength }}
    secrets:
      NX__TRIPPIN__API_KEY:
        description: 'The Trippin API Key'
        required: true
      NX__WEATHERBIT__API_KEY:
        description: 'The Weatherbit API Key'
        required: true
      NX_CLOUD_ACCESS_TOKEN:
        description: 'The NX Cloud API token'
        required: true

concurrency:
  group: build-test-${{ github.workflow }}-${{ github.ref }}

env:
  NX__TRIPPIN__API_KEY: ${{ secrets.NX__TRIPPIN__API_KEY }}
  NX__WEATHERBIT__API_KEY: ${{ secrets.NX__WEATHERBIT__API_KEY }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.affected.affected }}
      affectedLength: ${{ steps.affected.affectedLength }}
      affectedApps: ${{ steps.affected.affectedApps }}
      affectedAppsLength: ${{ steps.affected.affectedAppsLength }}
      affectedLibs: ${{ steps.affected.affectedLibs }}
      affectedLibsLength: ${{ steps.affected.affectedLibsLength }}
    steps:
      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Affected
        id: affected
        uses: ./.github/actions/nx-affected

  nx:
    name: Nx
    runs-on: ubuntu-latest
    needs: [setup]
    timeout-minutes: 10
    strategy:
      max-parallel: 2
      matrix:
        command:
          - [
              Build,
              'nx affected --target=build',
              'nx run-many --target=build --all',
            ]
          - [
              Lint,
              'nx-cloud record -- npx nx workspace-lint; pnpm nx-cloud record -- npx nx format:check; pnpm nx affected --target=lint',
              'nx-cloud record -- npx nx workspace-lint; pnpm nx-cloud record -- npx nx format:check; pnpm nx run-many --target=lint --all',
            ]
          - [
              Test,
              'nx affected --target=test --ci --code-coverage',
              'nx run-many --target=test --all --ci --code-coverage',
            ]
          - [
              Validate,
              'nx affected --target=validate',
              'nx run-many --target=validate --all',
            ]
          - [E2E, 'nx affected --target=e2e', 'nx run-many --target=e2e --all']
          - [
              'E2E (Start)',
              'nx affected --target=e2e --configuration=start',
              'nx run-many --target=e2e --configuration=start --all',
            ]
    steps:
      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          ignore-cypress-cache: ${{ !startsWith(matrix.command[0], 'E2E') }}

      - name: Affected ${{ matrix.command[0] }}
        if: inputs.affected == 'true'
        shell: bash
        run: |
          pnpm ${{ matrix.command[1] }} --parallel=4

      - name: ${{ matrix.command[0] }}
        if: inputs.affected != 'true'
        shell: bash
        run: |
          pnpm ${{ matrix.command[2] }} --parallel=6 --skip-nx-cache
