name: 'Build & Test'

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

  workflow_call:
    inputs:
      affected:
        description: Only build & test affected apps & libraries.
        type: boolean
        required: false
        default: true
      parallel:
        description: Max number of parallel processes per Nx target
        type: number
        required: false
        default: 3

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NX_AFFECTED: ${{ inputs.affected == 'true' || true }}
  NX_PARALLEL: ${{ inputs.parallel || 3 }}

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      # Enable tmate debugging of manually-triggered workflows
      # if the input option was provided.
      - name: Setup SSH debug session
        uses: mxschmitt/action-tmate@8b4e4ac71822ed7e0ad5fb3d1c33483e9e8fb270 # tag=v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Workspace lint
        run: pnpm nx-cloud record -- npx nx workspace-lint

      - name: Format Check
        run: pnpm nx-cloud record -- npx nx format:check

      - name: Affected Lint
        if: ${{ env.NX_AFFECTED == 'true' }}
        run: pnpm nx affected --target=lint --parallel=${{ env.NX_PARALLEL }}

      - name: Lint
        if: ${{ env.NX_AFFECTED == 'false' }}
        run: pnpm nx run-many --target=lint --all --parallel=${{ env.NX_PARALLEL }}

      - name: Affected Test
        if: ${{ env.NX_AFFECTED == 'true' }}
        run: pnpm nx affected --target=test --parallel=${{ env.NX_PARALLEL }} --ci --code-coverage

      - name: Test
        if: ${{ env.NX_AFFECTED == 'false' }}
        run: pnpm nx run-many --target=test --all --parallel=${{ env.NX_PARALLEL }} --ci --code-coverage

      - name: Affected Build
        if: ${{ env.NX_AFFECTED == 'true' }}
        run: pnpm nx affected --target=build --parallel=${{ env.NX_PARALLEL }}

      - name: Build
        if: ${{ env.NX_AFFECTED == 'false' }}
        run: pnpm nx run-many --target=build --all --parallel=${{ env.NX_PARALLEL }}

      - name: Affected E2E
        if: ${{ env.NX_AFFECTED == 'true' }}
        run: pnpm nx affected --target=build --parallel=${{ env.NX_PARALLEL }}

      - name: Affected E2E
        if: ${{ env.NX_AFFECTED == 'true' }}
        uses: cypress-io/github-action@f9e9419e05e5b83168d397d9c1d8d40ea179901e # tag=v4.0.0
        with:
          install: false
          command: pnpm nx affected --target=e2e --parallel=${{ env.NX_PARALLEL }}

      - name: E2E
        if: ${{ env.NX_AFFECTED == 'false' }}
        uses: cypress-io/github-action@f9e9419e05e5b83168d397d9c1d8d40ea179901e # tag=v4.0.0
        with:
          install: false
          command: pnpm nx run-many --target=e2e --all --parallel=${{ env.NX_PARALLEL }}
