name: 'Build & Test'

on:
  workflow_call:
    inputs:
      affected:
        description: Only build & test affected apps & libraries.
        type: boolean
        required: false
        default: true
    outputs:
      affected:
        description: 'Affected apps & libraries'
        value: ${{ jobs.setup.outputs.affected }}
      affectedLength:
        description: 'Number of affected apps & libraries'
        value: ${{ jobs.setup.outputs.affectedLength }}
      affectedApps:
        description: 'Affected apps'
        value: ${{ jobs.setup.outputs.affectedApps }}
      affectedAppsLength:
        description: 'Number of affected apps'
        value: ${{ jobs.setup.outputs.affectedAppsLength }}
      affectedLibs:
        description: 'Affected libraries'
        value: ${{ jobs.setup.outputs.affectedLibs }}
      affectedLibsLength:
        description: 'Number of affected libraries'
        value: ${{ jobs.setup.outputs.affectedLibsLength }}
    secrets:
      NX__TRIPPIN__API_KEY:
        description: 'The Trippin API Key'
        required: true
      NX__WEATHERBIT__API_KEY:
        description: 'The Weatherbit API Key'
        required: true
      NX_CLOUD_ACCESS_TOKEN:
        description: 'The NX Cloud API token'
        required: true

concurrency:
  group: build-test-${{ github.workflow }}-${{ github.ref }}

env:
  NX__TRIPPIN__API_KEY: ${{ secrets.NX__TRIPPIN__API_KEY }}
  NX__WEATHERBIT__API_KEY: ${{ secrets.NX__WEATHERBIT__API_KEY }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        node: [lts]
        experimental: [false]
        include:
          - node: latest
            experimental: true
    env:
      NX_CLOUD_ENV_NAME: node-${{ matrix.node }}
    outputs:
      affected: ${{ steps.affected.outputs.affected }}
      affectedLength: ${{ steps.affected.outputs.affectedLength }}
      affectedApps: ${{ steps.affected.outputs.affectedApps }}
      affectedNonE2E: ${{ steps.affected.outputs.affectedNonE2E }}
      affectedE2E: ${{ steps.affected.outputs.affectedE2E }}
      affectedAppsLength: ${{ steps.affected.outputs.affectedAppsLength }}
      affectedLibs: ${{ steps.affected.outputs.affectedLibs }}
      affectedLibsLength: ${{ steps.affected.outputs.affectedLibsLength }}
      hasAffected: ${{ steps.affected.outputs.hasAffected }}
      allE2E: ${{ steps.affected.outputs.allE2E }}
      allNonE2E: ${{ steps.affected.outputs.allNonE2E }}
      allLibs: ${{ steps.affected.outputs.allLibs }}
      e2e: ${{ steps.outputs.outputs.e2e }}
    steps:
      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}

      - name: Affected
        id: affected
        uses: ./.github/actions/nx-affected

      - name: Outputs
        id: outputs
        shell: bash
        run: |
          e2e=${{ steps.affected.outputs.allE2E }}

          if [ ${{ inputs.affected }} = true ]; then
            e2e=${{ steps.affected.outputs.affectedE2E }}
          fi

          echo e2e=$e2e
          echo ::set-output name=e2e::$e2e

      - name: Workspace Lint
        if: matrix.node == 'lts'
        shell: bash
        run: |
          pnpm nx-cloud record -- npx nx workspace-lint

      - name: Format
        if: matrix.node == 'lts'
        shell: bash
        run: |
          pnpm nx-cloud record -- npx nx format:check

      - name: Affected Lint
        if: inputs.affected == true && matrix.node == 'lts'
        shell: bash
        run: |
          pnpm nx affected --target=lint --parallel=3

      - name: Lint
        if: inputs.affected != true && matrix.node == 'lts'
        shell: bash
        run: |
          pnpm nx run-many --target=lint --all --parallel=3

      - name: Affected Build
        if: inputs.affected == true
        shell: bash
        run: |
          pnpm nx affected --target=build --parallel=3

      - name: Build
        if: inputs.affected != true
        shell: bash
        run: |
          pnpm nx run-many --target=build --all --parallel=3

  nx:
    runs-on: ubuntu-latest
    needs: [setup]
    if: needs.setup.outputs.hasAffected == 'true' || inputs.affected != true
    timeout-minutes: 5
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      # max-parallel: 2
      fail-fast: false
      matrix:
        node: [lts]
        command: [test, validate]
        experimental: [false]
        include:
          - node: latest
            command: validate
            experimental: true
    name: node-${{ matrix.node }} - ${{ matrix.command }}
    env:
      NX_CLOUD_ENV_NAME: node-${{ matrix.node }}
    steps:
      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          ignore-cypress-cache: ${{ !startsWith(matrix.command, 'e2e') }}
          node-version: ${{ matrix.node }}

      - name: Affected Test
        if: inputs.affected == true && matrix.command == 'test'
        shell: bash
        run: |
          pnpm nx affected --target=test --ci --code-coverage --parallel=3

      - name: Test
        if: inputs.affected != true && matrix.command == 'test'
        shell: bash
        run: |
          pnpm nx run-many --target=test --all --ci --code-coverage --parallel=3

      - name: Affected Validate
        if: inputs.affected == true && matrix.command == 'validate'
        shell: bash
        run: |
          pnpm nx affected --target=validate --parallel=2

      - name: Validate
        if: inputs.affected != true && matrix.command == 'validate'
        shell: bash
        run: |
          pnpm nx run-many --target=validate --all --parallel=2

  e2e:
    runs-on: ubuntu-latest
    needs: [setup]
    if: needs.setup.outputs.hasAffected == 'true' || inputs.affected != true
    timeout-minutes: 15
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      # max-parallel: 2
      fail-fast: false
      matrix:
        node: [lts]
        app: ${{ toJson(needs.setup.outputs.e2e) }}
        command: [e2e, e2e-start, e2e-serve, e2e-serve-dev]
        experimental: [false]
        include:
          - node: latest
            app: api-gateway-trippin-e2e
            command: e2e-serve
            experimental: true
          - node: latest
            app: api-gateway-trippin-e2e
            command: e2e-serve-dev
            experimental: true
          - node: latest
            app: nextjs-trippin-e2e
            command: e2e
            experimental: true
    name: node-${{ matrix.node }} - ${{ matrix.command }}
    env:
      NX_CLOUD_ENV_NAME: node-${{ matrix.node }}
    steps:
      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          ignore-cypress-cache: ${{ !startsWith(matrix.command, 'e2e') }}
          node-version: ${{ matrix.node }}

      - name: E2E
        timeout-minutes: 8
        if: matrix.command == 'e2e'
        uses: cypress-io/github-action@be2de7b1fe1cdafb4a3c8da0a3746476ef636b65 # tag=v4.1.0
        with:
          install: false
          command: |
            pnpm nx run ${{ matrix.app }}:${{ matrix.command }}

      - name: E2E (Start)
        timeout-minutes: 8
        if: matrix.command == 'e2e-start'
        uses: cypress-io/github-action@be2de7b1fe1cdafb4a3c8da0a3746476ef636b65 # tag=v4.1.0
        with:
          install: false
          command: |
            pnpm nx run ${{ matrix.app }}:${{ matrix.command }} --configuration=start

      - name: E2E (Serve)
        timeout-minutes: 8
        if: matrix.command == 'e2e-serve'
        uses: cypress-io/github-action@be2de7b1fe1cdafb4a3c8da0a3746476ef636b65 # tag=v4.1.0
        with:
          install: false
          command: |
            pnpm nx run ${{ matrix.app }}:${{ matrix.command }} --configuration=serve

      - name: E2E (Serve Dev)
        timeout-minutes: 8
        if: matrix.command == 'e2e-serve-dev'
        uses: cypress-io/github-action@be2de7b1fe1cdafb4a3c8da0a3746476ef636b65 # tag=v4.1.0
        with:
          install: false
          command: |
            pnpm nx run ${{ matrix.app }}:${{ matrix.command }} --configuration=serve-dev
