name: 'Code Analysis - Sonar'

on:
  workflow_call:
    secrets:
      NX__TRIPPIN__API_KEY:
        description: 'The Trippin API Key'
        required: true
      NX_CLOUD_ACCESS_TOKEN:
        description: 'The NX Cloud API token'
        required: true

  workflow_dispatch:

concurrency:
  group: code-analysis--sonar-${{ github.workflow }}-${{ github.ref }}

env:
  NX__TRIPPIN__API_KEY: ${{ secrets.NX__TRIPPIN__API_KEY }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CLOUD_ENV_NAME: node-lts

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          ignore-cypress-cache: ${{ !startsWith(matrix.command, 'e2e') }}
          node-version: ${{ matrix.node }}

      - name: Lint
        shell: bash
        run: |
          pnpm nx run-many --target=lint --all --parallel=3 --configuration=reports

      - name: Test
        shell: bash
        run: |
          pnpm nx run-many --target=test --all --ci --code-coverage --parallel=3

      - name: Get Nx-mesh version
        id: version
        uses: notiz-dev/github-action-json-property@a5a9c668b16513c737c3e1f8956772c99c73f6e8 # v0.2.0
        with:
          path: 'libs/nx-mesh/package.json'
          prop_path: 'version'

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@cb201f3b2d7a38231a8c042dfea4539c8bea180b # v1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectVersion=${{ steps.version.outputs.prop }}
