name: 'Code Analysis'

on:
  workflow_call:
    secrets:
      NX__TRIPPIN__API_KEY:
        description: 'The Trippin API Key'
        required: true
      NX_CLOUD_ACCESS_TOKEN:
        description: 'The NX Cloud API token'
        required: true

  workflow_dispatch:

concurrency:
  group: code-analysis-${{ github.workflow }}-${{ github.ref }}

env:
  NX__TRIPPIN__API_KEY: ${{ secrets.NX__TRIPPIN__API_KEY }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CLOUD_ENV_NAME: node-lts

jobs:
  sonar:
    name: Sonar
    uses: ./.github/workflows/code-analysis--sonar.yml
    secrets: inherit
