# name: 'Pull Request'

# on:
#   pull_request:
#     branches:
#       - main

# concurrency:
#   group: pr-${{ github.workflow }}-${{ github.ref }}

name: 'Pull Request'

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.workflow }}-${{ github.ref }}

# jobs:
#   build-test:
#     uses: ./.github/workflows/build-test.yml
#     secrets: inherit

#   # deploy:
#   #   needs: [build-test]
#   #   uses: ./.github/workflows/deploy.yml
#   #   with:
#   #     apps: ${{ needs.build-test.outputs.affectedApps }}
#   #   secrets: inherit

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: ./.github/workflows/nx-cloud-main.yml
    secrets: inherit
    with:
      number-of-agents: 1
      parallel-commands: |
        npx nx-cloud record -- npx nx workspace-lint
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=build --parallel=3
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci --code-coverage
        npx nx affected --target=validate --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: ./.github/workflows/nx-cloud-agents.yml
    secrets: inherit
    with:
      number-of-agents: 1
