name: 'Pull Request'

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.workflow }}-${{ github.ref }}

env:
  NX__TRIPPIN__API_KEY: ${{ secrets.NX__TRIPPIN__API_KEY }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CLOUD_ENV_NAME: node-lts

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml
    secrets: inherit
    with:
      affected: true

  sonar:
    needs: [build-test]
    name: Sonar
    uses: ./.github/workflows/sonar.yml
    secrets: inherit

  deploy:
    needs: [build-test]
    uses: ./.github/workflows/deploy.yml
    with:
      apps: ${{ needs.build-test.outputs.affectedApps }}
    secrets: inherit

  alpha:
    name: Release Alpha
    needs: [build-test]
    if: (${{ github.event.pull_request.head.repo.full_name }} == ${{ github.repository }}) && ${{ !startsWith(github.event.pull_request.head.ref,'changeset-release') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm nx run-many --target=build --configuration=production --all

      - name: Modify Workspace File
        run: sed -e 's/libs\//dist\/libs\//g' pnpm-workspace.yaml > pnpm-workspace-dist.yaml && mv pnpm-workspace-dist.yaml pnpm-workspace.yaml

      - name: Release Alpha Snapshot
        id: snapshot
        uses: the-guild-org/changesets-snapshot-action@eeff4d8aecffd035c3d5513d9811f07893737425 # v0.0.1
        with:
          tag: alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
