name: 'Pull Request'

on:
  pull_request:

concurrency:
  group: pr--${{ github.workflow }}--${{ github.ref }}

env:
  NX__TRIPPIN__API_KEY: ${{ secrets.NX__TRIPPIN__API_KEY }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  setup:
    uses: ./.github/workflows/setup-job-test.yml
    secrets: inherit
    with:
      node_version: lts
      save_cache: true

  # lint:
  #   uses: ./.github/workflows/_lint.yml
  #   secrets: inherit
  #   with:
  #     affected: true
  #     node_version: lts
  #     save_cache: true

  # build:
  #   needs: [lint]
  #   uses: ./.github/workflows/_build.yml
  #   secrets: inherit
  #   with:
  #     affected: true
  #     node_version: lts

  # test:
  #   needs: [build]
  #   uses: ./.github/workflows/_test.yml
  #   secrets: inherit
  #   with:
  #     affected: true
  #     node_version: lts

  # e2e:
  #   needs: [build]
  #   uses: ./.github/workflows/_e2e.yml
  #   secrets: inherit
  #   with:
  #     affected: true
  #     node_version: lts

  # generators:
  #   needs: [build]
  #   uses: ./.github/workflows/_generators.yml
  #   secrets: inherit
  #   with:
  #     affected: true
  #     node_version: lts

  # build-test:
  #   uses: ./.github/workflows/build-test.yml
  #   secrets: inherit
  #   with:
  #     affected: true

  # code-analysis:
  #   needs: [build-test]
  #   name: Code Analysis
  #   uses: ./.github/workflows/code-analysis.yml
  #   secrets: inherit

  # deploy:
  #   needs: [build-test]
  #   uses: ./.github/workflows/deploy.yml
  #   with:
  #     apps: ${{ needs.build-test.outputs.affectedApps }}
  #   secrets: inherit

  # alpha:
  #   name: Release Alpha
  #   needs: [build-test]
  #   if: (${{ github.event.pull_request.head.repo.full_name }} == ${{ github.repository }}) && ${{ !startsWith(github.event.pull_request.head.ref,'changeset-release') }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
  #       with:
  #         fetch-depth: 0

  #     - name: Setup Job
  #       uses: ./.github/actions/setup-job

  #     - name: Build
  #       run: pnpm nx run-many --target=build --configuration=production --all

  #     - name: Modify Workspace File
  #       run: sed -e 's/libs\//dist\/libs\//g' pnpm-workspace.yaml > pnpm-workspace-dist.yaml && mv pnpm-workspace-dist.yaml pnpm-workspace.yaml

  #     - name: Release Alpha Snapshot
  #       id: snapshot
  #       uses: the-guild-org/changesets-snapshot-action@eeff4d8aecffd035c3d5513d9811f07893737425 # v0.0.1
  #       with:
  #         tag: alpha
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
