# name: 'Pull Request'

# on:
#   pull_request:
#     branches:
#       - main

# concurrency:
#   group: pr-${{ github.workflow }}-${{ github.ref }}

name: 'Pull Request'

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.workflow }}-${{ github.ref }}

# jobs:
#   build-test:
#     uses: ./.github/workflows/build-test.yml
#     secrets: inherit

#   # deploy:
#   #   needs: [build-test]
#   #   uses: ./.github/workflows/deploy.yml
#   #   with:
#   #     apps: ${{ needs.build-test.outputs.affectedApps }}
#   #   secrets: inherit

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      affectedAgents: ${{ steps.affectedAgents.agents }}
      affectedAgentsLength: ${{ steps.affectedAgents.agentsLength }}
    steps:
      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Affected Agents Matrix
        id: affectedAgents
        uses: ./.github/actions/set-nx-agents-matrix

  affected:
    name: Affected
    if: needs.setup.outputs.affectedAgentsLength > 1
    runs-on: ubuntu-latest
    needs: [setup]
    strategy:
      matrix:
        agent:
          - ${{fromJson(needs.setup.outputs.affectedAgents)}}
    steps:
      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

    # name: Nx Cloud - Main Job
    # uses: ./.github/workflows/nx-cloud-main.yml
    # secrets: inherit
    # with:
    #   number-of-agents: 1
    #   parallel-commands: |
    #     npx nx-cloud record -- npx nx workspace-lint
    #     npx nx-cloud record -- npx nx format:check
    #   parallel-commands-on-agents: |
    #     npx nx affected --target=build --parallel=3
    #     npx nx affected --target=lint --parallel=3
    #     npx nx affected --target=test --parallel=3 --ci --code-coverage
    #     npx nx affected --target=validate --parallel=3

  # agents:
  #   name: Nx Cloud - Agents
  #   uses: ./.github/workflows/nx-cloud-agents.yml
  #   secrets: inherit
  #   with:
  #     number-of-agents: 1
