name: 'Pull Request'

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.workflow }}-${{ github.ref }}

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml
    secrets: inherit
    with:
      affected: false

  deploy:
    needs: [build-test]
    uses: ./.github/workflows/deploy.yml
    with:
      apps: ${{ needs.build-test.outputs.affectedApps }}
    secrets: inherit
