name: 'Release'

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}

env:
  NX__TRIPPIN__API_KEY: ${{ secrets.NX__TRIPPIN__API_KEY }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CLOUD_ENV_NAME: node-lts

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml
    with:
      affected: false
    secrets: inherit

  code-analysis:
    needs: [build-test]
    name: Code Analysis
    uses: ./.github/workflows/code-analysis.yml
    secrets: inherit

  release:
    needs: [build-test]
    name: Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    steps:
      # Enable tmate debugging of manually-triggered workflows
      # if the input option was provided.
      - name: Setup SSH debug session
        uses: mxschmitt/action-tmate@28f608baaa037465aa887c21a7924e9e6b66a9e0 # v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: Check out repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/workflows/setup.yml

      - name: Build
        run: pnpm nx run-many --target=build --configuration=production --all

      - name: Modify Workspace File
        run: sed -e 's/libs\//dist\/libs\//g' pnpm-workspace.yaml > pnpm-workspace-dist.yaml && mv pnpm-workspace-dist.yaml pnpm-workspace.yaml

      # - name: Set GitHub Packages registry
      #   uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
      #   with:
      #     registry-url: 'https://npm.pkg.github.com'

      - name: Create Release Pull Request or Publish packages
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm changeset publish
          commit: 'ci(changesets): version packages'
          title: 'ci(changesets): version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  next:
    name: Next Release
    needs: [release]
    if: needs.release.outputs.published != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/workflows/setup.yml

      - name: Build
        run: pnpm nx run-many --target=build --configuration=production --all

      - name: Modify Workspace File
        run: sed -e 's/libs\//dist\/libs\//g' pnpm-workspace.yaml > pnpm-workspace-dist.yaml && mv pnpm-workspace-dist.yaml pnpm-workspace.yaml

      - name: Release Snapshot
        id: snapshot
        uses: the-guild-org/changesets-snapshot-action@eeff4d8aecffd035c3d5513d9811f07893737425 # v0.0.1
        with:
          tag: next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy:
    needs: [release]
    if: needs.release.outputs.published == 'true'
    uses: ./.github/workflows/deploy.yml
    with:
      apps: ${{ needs.build-test.outputs.affectedApps }}
      production: true
    secrets: inherit
