name: Sync labels

permissions:
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/stale.yml

  schedule:
    # Checkout for updates daily at midnight
    - cron: '0 0 * * *'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stale:
    runs-on: ubuntu-20.04
    steps:
      - name: Sync Labels
        uses: actions/stale@99b6c709598e2b0d0841cd037aaf1ba07a4410bd # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          stale-issue-message: |
            > **Warning**

            This issue is stale because it has been open for 60 days with no activity. 💤

            Either remove the `stale` label or leave a comment else this issue will be closed in 7 days.
          stale-pr-message: |
            > **Warning**

            This pull request is stale because it has been open for 60 days with no activity. 💤

            Either remove the `stale` label, leave a comment or push a commit else this pull request will be closed in 7 days.
          close-issue-message: 'This issue was closed because it has been stale for 67 days with no activity.'
