name: 'Setup'

on:
  workflow_call:
    inputs:
      ignore-cypress-cache:
        description: Skip the restore of global Cypress cache (if cache is found)
        required: false
        default: false
        type: boolean
      node-version:
        description: The node version to use.
        required: false
        default: 'config'
        type: string
      save-cache:
        description: Save cache
        required: false
        default: false
        type: boolean
    secrets:
      NX_CLOUD_ACCESS_TOKEN:
        description: 'The NX Cloud API token'
        required: true

  workflow_dispatch:

concurrency:
  group: setup-${{ github.workflow }}-${{ github.ref }}

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CLOUD_ENV_NAME: node-lts

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3

      # Node

      - name: Setup Volta
        if: inputs.node-version == 'config'
        uses: volta-cli/action@25888009cd70dbe17a140f1c56d93f8c09f7bcef # v4.0.0

      - name: Setup Volta
        if: inputs.node-version != 'config'
        uses: volta-cli/action@25888009cd70dbe17a140f1c56d93f8c09f7bcef # v4.0.0
        with:
          node-version: ${{ inputs.node-version }}

      # pnpm

      - uses: pnpm/action-setup@v2.2.4
        with:
          run_install: false
          version: 7

      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # Restore Cache

      - name: Restore Cypress Cache
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # v3
        id: cypress-cache
        if: inputs.ignore-cypress-cache != true
        with:
          path: |
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ inputs.node-version }}-cypress-dep-cache-v2-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.node-version }}-cypress-dep-cache-v2-

      - name: Restore PNPM global cache
        uses: actions/cache/restore@v3.2.1 # v3
        id: pnpm-global-cache
        if: steps.pnpm-repo-cache.outputs.cache-hit != 'true'
        with:
          path: |
            ${{ steps.pnpm-cache-dir-path.outputs.STORE_PATH }}
          key: ${{ runner.os }}-${{ inputs.node-version }}-pnpm-global-cache-v2-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.node-version }}-pnpm-global-cache-v2-

      # - name: Restore local node_modules cache
      #   uses: actions/cache/restore@v3.2.1 # v3
      #   id: pnpm-repo-cache
      #   with:
      #     path: |
      #       **/node_modules
      #       !**/node_modules/.cache/nx
      #     key: ${{ runner.os }}-${{ inputs.node-version }}-pnpm-dep-cache-v2-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-${{ inputs.node-version }}-pnpm-dep-cache-v2-

      # Install

      - name: Install Node Dependencies
        shell: bash
        run: |
          pnpm install --frozen-lockfile

      # Nx

      - name: Nx Shas
        uses: nrwl/nx-set-shas@a80e36fdf700047d299324529b0f0eadc1a38cb2 # tag=v2.2.2

      # Save Cache

      - name: Save Cypress Cache
        uses: actions/cache/save@v3.2.1 # v3
        if: inputs.save-cache == true
        with:
          path: |
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ inputs.node-version }}-cypress-dep-cache-v2-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Save PNPM global cache
        uses: actions/cache/save@v3.2.1 # v3
        if: inputs.save-cache == true
        with:
          path: |
            ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ inputs.node-version }}-pnpm-global-cache-v2-${{ hashFiles('**/pnpm-lock.yaml') }}

      # - name: Save local node_modules cache
      #   uses: actions/cache/save@v3.2.1 # v3
      #   if: inputs.save-cache == true
      #   with:
      #     path: |
      #       **/node_modules
      #       !**/node_modules/.cache/nx
      #     key: ${{ runner.os }}-${{ inputs.node-version }}-pnpm-dep-cache-v2-${{ hashFiles('**/pnpm-lock.yaml') }}
